[build]
builder = "nixpacks"
buildCommand = "cd packages/backend && npm install && npm run build"
providers = ["node"]

[deploy]
startCommand = "cd packages/backend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"