[build]
builder = "nixpacks"
buildCommand = "cd packages/backend && bun install && bun run build"

[deploy]
startCommand = "cd packages/backend && bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"